yii/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;

use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SearchForm;
use app\models\Book;
use app\models\Author;


use yii\helpers\Html;
use yii\i18n\Formatter;
Yii::$app->formatter->locale = 'ru-RU';

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout','add','update','submitadd','submitedit','show'],
                'rules' => [
                    [
                        'actions' => ['logout','add','update','submitadd','submitedit','show'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

  public function actionIndex()
  {

    $modelBook   = new Book;
    $modelAuthor = new Author();
    $modelSearch = new SearchForm();

    $authors = $modelAuthor->getNamesArray();
    $data    = $modelBook->find()->with('author')->all(); //


    return $this->render('index', array(
        'data' => $data,
        'model'=>$modelBook,
        'search'=>$modelSearch,
        'authors' => $authors,
        'guest'=>\Yii::$app->user->isGuest )
    );
  }

  public function actionSearch()
  {
    $books = Book::find();

    $search_name       = Yii::$app->request->post('SearchForm')['name'];
    $search_yearstart = strtotime(Yii::$app->request->post('SearchForm')['year_start']);
    $search_yearend = strtotime(Yii::$app->request->post('SearchForm')['year_end']);
    $search_author = Yii::$app->request->post('SearchForm')['author_id'];

    $mult = false;
    if (!empty($search_name)) {
      $books->andWhere(['like', 'name', $search_name]);
      $mult = true;
    }
    if (!empty($search_yearstart)) {
      $books->andWhere(['>=', 'date', $search_yearstart]);
      $mult = true;
    }
    if (!empty($search_yearend)) {
      $books->andWhere(['<=', 'date', $search_yearend]);
      $mult = true;
    }
    if (!empty($search_author)) {
      $books->andWhere(['author_id'=> $search_author]);
      $mult = true;
    }
    $selection = $books->all();
    $dataArray = array();
    foreach ($selection as $book) {
      $bookData = [
        'id'=>$book->id,
        'name'=>$book->name,
        'preview'=>'<a href="'.$book->getImageFileUrl('preview','/rgkgroup/uploads/empty.jpg').'" class="thickbox">
                      <img src="'.$book->getThumbFileUrl('preview', 'thumb', '/rgkgroup/uploads/thumb_empty.jpg').'" />
                    </a>',
        'author'=>$book->author->firstname.' '.$book->author->lastname,
        'date_release'=>[
          'display'=>Yii::$app->formatter->asDate($book->date),
          'timestamp'=>$book->date
        ],
        'date_create'=>[
          'display'=>($book->date_create <  time()-3600*24)? Yii::$app->formatter->asDateTime($book->date_create) : str_replace('день назад','вчера',Yii::$app->formatter->asRelativeTime($book->date_create)),
          'timestamp'=>$book->date_create
        ],
      ];
      if (!\Yii::$app->user->isGuest) {
        $bookData['edit'] = Html::a(' ред.', array('site/update', 'id'=>$book->id), array('class'=>'glyphicon glyphicon-edit icon-edit','bid'=>$book->id));
        $bookData['update'] = Html::a(' просм.', array('site/show', 'id'=>$book->id), array('class'=>'glyphicon glyphicon-eye-open icon-view','bid'=>$book->id));
        $bookData['delete'] = Html::a(' удал.', array('site/delete', 'id'=>$book->id), array('class'=>'glyphicon glyphicon-trash icon-trash','bid'=>$book->id));
      }
      $dataArray[] = $bookData;
    }
    Yii::$app->response->format = Response::FORMAT_JSON;
    return ['data'=>$dataArray];
  }

  public function actionShow($id)
  {
    $modelBook = Book::find()->where(['id' => $id])->one();
    return $this->renderPartial('view', ['book' =>  $modelBook]);
  }

  public function actionDelete($id)
  {
    Yii::$app->response->format = Response::FORMAT_JSON;
    $modelBook = Book::find()->where(['id' => $id])->one();
    if($modelBook && $modelBook->delete()) return true;
    return false;
  }


    public function actionAdd()
    {
      $modelBook = new Book();
      $modelAuthor = new Author();
      $authors = $modelAuthor->getNamesArray();

      return $this->renderPartial('addfrom', ['model' =>  $modelBook,'authors' => $authors]);
    }

    public function actionSubmitadd()
    {
      Yii::$app->response->format = Response::FORMAT_JSON;
      $model = new Book();
      $model->load(Yii::$app->request->post());

      $modelAuthor = new Author();
      $authors = $modelAuthor->getNamesArray();


      if($model->load(Yii::$app->request->post()) && $model->save()) {
          return array('update'=>true);
      }
      else
      {
          return array($this->renderPartial('addfrom', ['model' => $model,'authors' => $authors]));
      }
    }

    public function actionUpdate($id)
    {
      $request = Yii::$app->request;
      $modelBook = Book::find()->where(['id' => $id])->one();
      $modelAuthor = new Author();
      $authors = $modelAuthor->getNamesArray();

      if ($request->isAjax)
        return $this->renderPartial('editform', ['model' =>  $modelBook,'authors' => $authors,'ajax'=>true]);
      else
        return $this->render('editform', ['model' =>  $modelBook,'authors' => $authors,'ajax'=>false]);
    }

    public function actionSubmitupdate($id)
    {
      Yii::$app->response->format = Response::FORMAT_JSON;
      $model = Book::find()->where(['id' => $id])->one();
      $model->load(Yii::$app->request->post());

      $modelAuthor = new Author();
      $authors = $modelAuthor->getNamesArray();

      if($model->load(Yii::$app->request->post()) && $model->save()) {
        return array('update'=>true);
      }
      else
      {
        return array($this->renderPartial('editform', ['model' => $model,'authors' => $authors]));
      }
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

yii/views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

yii/views/site/addfrom.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;

?>
<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Закрыть</span></button><br />
<div id="success"> </div> <!-- For success message -->

<div class="gb-user-form">

    <?php $form = ActiveForm::begin([
      'action' => 'site/submitadd',
      'method' => 'post',
      'options' => [
        'class' => 'add-form',
        'enableClientValidation' => false,
        'enctype' => 'multipart/form-data',
      ]]); ?>

      <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>
      <?= $form->field($model, 'author_id')->dropDownList($authors,['prompt'=>'Выберите автора']) ?>
      <?= $form->field($model, 'date')->textInput(['maxlength' => 255,'type'=> 'date']) ?>
      <?= $form->field($model, 'preview')->fileInput(['maxlength' => 255]) ?>

    <div class="form-group text-right">
        <?= Html::submitButton('Добавить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div> 

yii/views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mailer->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

yii/views/site/editform.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;

?>
<?php if($ajax) { ?>
<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Закрыть</span></button><br />
<?php }
else {
  $this->registerJsFile('/rgkgroup/scripts/index.js',['depends'=>'app\assets\AppAsset']);
  ?>
  <h3>Редактирование свойств книги</h3>
 <?php   } ?>
<div id="success"> </div> <!-- For success message -->

<div class="edit-user-form">

    <?php $form = ActiveForm::begin([
      'action' => '@web/site/submitupdate/'.$model->id,
      'method' => 'post',
      'options' => [
        'class' => 'edit-form',
        'enableClientValidation' => false,
        'enctype' => 'multipart/form-data',
        'bid' => $model->id
      ]]); ?>

      <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>
      <?= $form->field($model, 'author_id')->dropDownList($authors) ?>
      <?= $form->field($model, 'date')->textInput(['maxlength' => 255, 'type'=> 'date', 'value'=>strftime('%Y-%m-%d',$model->date)]) ?>
      <?= $form->field($model, 'preview')->fileInput(['maxlength' => 255]) ?>

    <div class="form-group text-right">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div> 

yii/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

yii/views/site/index.php
<?php
  use yii\helpers\Html;
  use yii\bootstrap\ActiveForm;
  use yii\helpers\ArrayHelper;

  $this->registerCssFile("/rgkgroup/scripts/datatables/css/jquery.dataTables.min.css");
  $this->registerJsFile('/rgkgroup/scripts/datatables/js/jquery.dataTables.js',['depends'=>'app\assets\AppAsset']);
  $this->registerJsFile('/rgkgroup/scripts/index.js',['depends'=>'app\assets\AppAsset']);

$this->title = 'Архив книг:: My Yii Application';

?>
<div class="site-index">


    <h1>Архив книг</h1>


    <div class="body-content">

        <div class="row">
          <h3>Поиск:</h3>

          <?php $form = ActiveForm::begin([
            'action' => 'site/search',
            'id' => 'search-form',
            'options' => [
              'class' => 'search-form',
              'enableClientValidation' => false,
              'enctype' => 'multipart/form-data',
            ]]);
          ?>

          <div class="search-user-form col-lg-4">

            <?php echo $form->field($search, 'author_id')->dropDownList($authors,['class' => 'form-control','prompt'=>'автор'])->label(false); ?>
          </div>

          <div class="search-user-form col-lg-3">

            <?php echo $form->field($search, 'name',['template' => '{label} {input}<span id="searchclear" class="glyphicon glyphicon-remove-circle"></span>{error}{hint}'])->textInput(['maxlength' => 255, 'class' => 'form-control', 'placeholder'=>'название книги'])->label(false); ?>

          </div>
          <div class="search-user-form col-lg-1">

          </div>
        </div>
        <div class="row">
          <div class="search-user-form col-lg-2">
						<label>Дата издания от:</label>
          </div>
          <div class="search-user-form col-lg-2">
                <?php echo $form->field($search, 'year_start')->textInput(['type'=>'date','maxlength' => 10,'class' => 'form-control', 'placeholder'=>'Дата издания от'])->label(false); ?>
          </div>
          <div class="search-user-form col-lg-1">
						<label>до:</label>
          </div>
          <div class="search-user-form col-lg-2">
                <?php echo $form->field($search, 'year_end')->textInput(['type'=>'date','maxlength' => 10,'class' => 'form-control', 'placeholder'=>'Дата издания до'])->label(false); ?>
          </div>

          <div class="search-user-form col-lg-1">



						<div class="form-group text-right">
								<?= Html::submitButton('Искать', ['class' => 'btn btn-success']) ?>
						</div>


					</div>
        </div>
          <?php ActiveForm::end(); ?>

    </div>
  <hr />
  <div class="row">
		<div class="col-lg-11"></div>
		<div class="col-lg-1">
			<?php if(!$guest) { ?>
			<p><?php echo Html::a('Добавить книгу', array('site/add'), array('class'=>'btn btn-success add')); ?></p>
			<?php } ?>
		</div>
    </div>
		<div class="row">
			<div class="col-lg-13">

				<table class="display table table-striped table-hover" id="data-table">
					<thead>
						<tr>
								<th>ID</th>
								<th>Название</th>
								<th data-sorter="false">Превью</th>
								<th>Автор</th>
								<th>Дата выхода книги</th>
								<th>Дата добавления</th>
							<?php if(!$guest) { ?>
								<th colspan="3" data-sorter="false">Действия</th>
							<?php } ?>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
		</div>
  </div>


  <div class="modal fade" id="my-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-body">
         </div>
       </div>
     </div>
  </div>

</div>

yii/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>


    <div class="col-lg-offset-1" style="color:blue;">
        ДЕМО-вход: 	<strong>demo/demo</strong>.
				<br>
				<br>
    </div>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

yii/views/site/test.php
<?php

  use yii\helpers\VarDumper;

  echo VarDumper::dumpAsString($request,4);

?>

yii/views/site/view.php
<?php

  use yii\helpers\Html;
  use yii\i18n\Formatter;
  Yii::$app->formatter->locale = 'ru-RU';


?>
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Закрыть</span></button>

  <div id="model-<?php echo $book->id; ?>" class="model_view">
    <h2><?php echo $book->name; ?></h2>
    <h3><?php echo $book->author->firstname.' '.$book->author->lastname; ?></h3>
    <img src="<?php echo $book->getImageFileUrl('preview'); ?>"  />
    <p>Год Издания: <?php echo Yii::$app->formatter->asDate($book->date); ?></p>
    <p>Дата добавления в базу: <?php echo ($book->date_create <  time()-3600*24)? Yii::$app->formatter->asDateTime($book->date_create) : str_replace('день назад','вчера',Yii::$app->formatter->asRelativeTime($book->date_create)); ?></p>
    <p>Дата редактирования: <?php echo Yii::$app->formatter->asDateTime($book->date_update); ?></p>
  </div>